spring:
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    properties:
      hibernate:
        highlight_sql: true # dddd
        format_sql: true  # SQL pretty print
    hibernate:
      ddl-auto: create  # 테이블 자동 구성(드랍 & 생성)
    show-sql: true      # SQL 보기
  sql:
    init:
      data-locations: classpath*:db/h2/data.sql
  output:
    ansi:
      enabled: always # debug, trace
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: TRACE # hibernate
      springframework:
        orm:
          jpa: DEBUG

cloud:
  aws:
    s3:
      bucket:
    credentials:
      access-key:
      secret-key:
    region:
      static:
      auto: false
    stack:
      auto: false